<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <WarningsNotAsErrors>NU1604;NU1605;NU1902</WarningsNotAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Jaeger" Version="1.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.9.0.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Whaally.Domain\Whaally.Domain.csproj" />
    </ItemGroup>

</Project>
