<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.3" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Orleans.EventSourcing" />
    <PackageReference Include="Microsoft.Orleans.Serialization.Protobuf" />
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\Skyhop.Domain\Skyhop.Domain.csproj" />
    <ProjectReference Include="..\..\src\Whaally.Domain.Analyzers\Whaally.Domain.Analyzers.csproj" />
    <ProjectReference Include="..\..\src\Whaally.Domain.Infrastructure.OrleansHost.MartenPersistence\Whaally.Domain.Infrastructure.OrleansHost.MartenPersistence.csproj" />
    <ProjectReference Include="..\..\src\Whaally.Domain.Infrastructure.OrleansHost\Whaally.Domain.Infrastructure.OrleansHost.csproj" />
    <ProjectReference Include="..\..\src\Whaally.Domain\Whaally.Domain.csproj" />
  </ItemGroup>

</Project>