name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore /property:Configuration=Release

    - name: Build
      run: dotnet build --configuration Release /property:Version="${{ steps.semantic.outputs.new_release_version }}" /property:AssemblyVersion="${{steps.semantic.outputs.new_release_major_version}}" /property:AssemblyFileVersion=${{ steps.semantic.outputs.new_release_version }} /property:PackageReleaseNotes="${{ steps.semantic.outputs.new_release_notes }}"  --no-restore

    - name: Test
      run: dotnet test /property:Configuration=Release --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/main') || ${{ steps.semantic.outputs.new_release_version }} != ""
      run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}